const theme = {
  light: {
    theme: "light",
    bg: "#FFFFFF",
    background: "#1F4690",
    txt: "#000000",
    icon: "#9F0CE3",
    box: "#E3E7EC",
    barstyle: "dark-content",
    img: require("../../assets/image/Progress.png"),
    img1: require("../../assets/image/Progress1.png"),
    banner: require("../../assets/image/banner.png"),
    apple: require("../../assets/image/Apple.png"),
    boarding: require("../../assets/image/BG1.png"),
    line: require("../../assets/image/blueline1.png"),
    msg: require("../../assets/image/d1.png"),
    fpb: "#F5F5F5",
    chat: "#E3E7EC",
  },
  dark: {
    theme: "dark",
    bg: "#111111",
    background: "#000000",
    txt: "#FFFFFF",
    icon: "#9F0CE3",
    box: "#434E58",
    barstyle: "light-content",
    img: require("../../assets/image/Progressblack.png"),
    img1: require("../../assets/image/Progress1black.png"),
    banner: require("../../assets/image/banner1.png"),
    apple: require("../../assets/image/Apple1.png"),
    boarding: require("../../assets/image/BG.png"),
    line: require("../../assets/image/orangeline1.png"),
    msg: require("../../assets/image/d2.png"),
    fpb: "#434E58",
    chat: "#171725",
  },
};

export default theme;
